updating scripts to account for automatic flake.lock updates

diff --git a/scripts/nrb b/scripts/nrb
--- a/scripts/nrb
+++ b/scripts/nrb
@@ -1,7 +1,14 @@
 #!/usr/bin/env bash
 
 cd ~/nixfiles
+git pull
 git add -u
-([ -z $1 ] 2>/dev/null && git commit -m "$(date +%F--%T)") || git commit -m "$(date +%F--%T): \"$1\""
-git push
 sudo nixos-rebuild switch --show-trace
+status=$?
+if [ $status -eq 0 ]; then
+    ([ -z $1 ] 2>/dev/null && git commit -m "$(date +%F--%T)") || git commit -m "$(date +%F--%T): \"$1\""
+else
+    git restore --staged .
+    echo -e "'nixos-rebuild switch' failed: not committing changes"
+fi
+# git push
diff --git a/scripts/nupd b/scripts/nupd
--- a/scripts/nupd
+++ b/scripts/nupd
@@ -8,14 +8,14 @@ git pull
 # git merge main
 # git add -u
 sudo nixos-rebuild boot
-status=$?
-if [ $status -eq 0 ]; then
-    # git add -A ':!./flake.lock'
-    git commit -m "$(date +%F--%T): flake update" && git push
-else
-    echo -e "update failed with error $status"
-    # git restore flake.lock
-fi
+# status=$?
+# if [ $status -eq 0 ]; then
+#     # git add -A ':!./flake.lock'
+#     git commit -m "$(date +%F--%T): flake update" && git push
+# else
+#     echo -e "update failed with error $status"
+#     # git restore flake.lock
+# fi
 # git push
 # sudo nixos-rebuild boot
 hmu
